networks:
  default: mainnet-fork
compiler:
  evm_version: istanbul
  minify_source: false
  solc:
    version: 0.8.10
    optimize: true
    runs: 200
reports:
  exclude_paths:
    - contracts/test_helpers/*
  exclude_contracts:
    - ERC20
    - ERC721
    - ERC1155
    - Ownable
