dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
networks:
  default: mainnet-fork
compiler:  
  evm_version: istanbul
  minify_source: false
  solc:
    version: 0.8.16
    optimize: true
    runs: 200